import html as html_mod

from weasyprint import HTML


def generate_pdf_report(title: str, sections: list[dict], sources: list[str] | None = None) -> bytes:
    safe_title = html_mod.escape(title)

    sources_html = ""
    if sources:
        items = "".join(f'<li>{html_mod.escape(s)}</li>' for s in sources)
        sources_html = f"<h2>Sources</h2><ul>{items}</ul>"

    sections_html = ""
    for s in sections:
        heading = html_mod.escape(s.get("heading", ""))
        content = html_mod.escape(s.get("content", "")).replace("\n", "<br>")
        sections_html += f"""
        <div class="section">
            <h2>{heading}</h2>
            <p>{content}</p>
        </div>
        """

    html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    @page {{
        margin: 2.5cm 2cm;
        @bottom-center {{
            content: counter(page);
            font-size: 9pt;
            color: #888;
        }}
    }}
    body {{
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        font-size: 11pt;
        line-height: 1.6;
        color: #1a1a1a;
    }}
    h1 {{
        font-size: 24pt;
        color: #1a1a1a;
        border-bottom: 2px solid #333;
        padding-bottom: 10px;
        margin-bottom: 20px;
    }}
    h2 {{
        font-size: 16pt;
        color: #444;
        margin-top: 25px;
        border-bottom: 1px solid #ddd;
        padding-bottom: 5px;
    }}
    .section {{
        margin-bottom: 15px;
    }}
    .section p {{
        text-align: justify;
    }}
    ul {{
        padding-left: 20px;
    }}
    li {{
        margin-bottom: 4px;
    }}
    .meta {{
        color: #888;
        font-size: 9pt;
        margin-bottom: 30px;
    }}
</style>
</head>
<body>
    <h1>{safe_title}</h1>
    <div class="meta">Generated by MicroManus research agent</div>
    {sections_html}
    {sources_html}
</body>
</html>"""

    return HTML(string=html).write_pdf()
